### ISSUE TITLE
Add compatibility for Chromium-based browsers

### ISSUE THREAD

**Issue by 2br-2b** [swow2015/Who-sSellingMyInfo-#1]
I'm on making this extension work on Chromium-based browsers (like Brave, Opera, etc.) in my fork (https://github.com/2br-2b/Who-sSellingMyInfo-).

**Comment by oapostrophe** [comment]
Fantastic!  Let me know if you get a working version, if so I'd love to update here as well.

**Comment by 2br-2b** [comment]
Right now, it makes the popus, but due to some chromium security restrictions, it throws an error when clicking the button. I'll try to fix that, then submit a PR
