### ISSUE TITLE
Add persistent x-ing out

### ISSUE THREAD

**Issue by 2br-2b** [swow2015/Who-sSellingMyInfo-#11]
If you x-out the box on a website, it should store that and not keep popping up every time you reload the page.

Should it stay closed:
- Permanently?
- Until the browser is closed?
- For a certain period of time?

**Comment by oapostrophe** [comment]
What about having a "Don't remind me again" box you can check before closing, or something to that effect?

**Comment by 2br-2b** [comment]
I think that would work great! Would you like to work on this, or would you like me to?

Also, I would think the storage will be local, not synced between browsers

**Comment by oapostrophe** [comment]
I won't have any time to work on things until December as I'm gearing up for finals--you're welcome to work on it before then or I can try to implement it over break!

**Comment by 2br-2b** [comment]
I'm up for either. I'll probably also be pretty busy with finals here, but I may try to find time to work on this or, at the very least, on the javascript to store the pages

**Comment by 2br-2b** [comment]
I decided to just implement it myself in https://github.com/2br-2b/Who-sSellingMyInfo-/tree/persistent-x-out. The style for the checkbox isn't quite consistent with the rest of the popup, and I used a really hacky solution for some of the parts though, so I haven't submitted a pull request yet. Feel free to take whatever parts of this you would like!

**Comment by oapostrophe** [comment]
Closing development of this for the forseeable future, so won't include this in this Repo.
