### ISSUE TITLE
Add optional counter to keep track of what percentage of websites track your data

### ISSUE THREAD

**Issue by 2br-2b** [swow2015/Who-sSellingMyInfo-#13]
Make an opt-in "Stat tracker" that 1) stores data locally on your device, 2) displays what percentage of pages sell your personal info.

**Comment by oapostrophe** [comment]
I wonder if there's a way to add an opt-in to send this data to us in order to get use statistics.

**Comment by 2br-2b** [comment]
To do this, we would also need a server infrastructure, which I don't have the time to develop, as much as I would like to. Locally, however, should be  relatively easy

**Comment by 2br-2b** [comment]
When you have a chance, would you like to make a branch I can commit my progress on? I can make the Javascript, but I'm still working on my html skills, so I probably won't end up making the GUI for the popup. Regardless, I'll probably do most of my work after finals, so don't feel any need to get anything done soon.

**Comment by 2br-2b** [comment]
At the very least, though, I'll probably end up adding stub html, css, and javascript documents for the popup when I have a chance.

**Comment by 2br-2b** [comment]
Update: I added the basic functionality on my branch https://github.com/2br-2b/Who-sSellingMyInfo-/tree/stats . The page doesn't look that great, so I don't think it's ready to be merged yet, but it works. All of the basic functionality (besides adding the opt-in/out toggle) works.

**Comment by oapostrophe** [comment]
I can try to hack something together for the popup after finals.  I just created a branch called "counter," do you need me to give you any sort of permission to commit to it?

**Comment by 2br-2b** [comment]
No - I can just make a pull request to it with the little work I have done

**Comment by oapostrophe** [comment]
Closing out development of this extension for the forseeable future, so this won't be implemented in this Repo.
