### ISSUE TITLE
Change more info link

### ISSUE THREAD

**Issue by 2br-2b** [swow2015/Who-sSellingMyInfo-#2]
We should find a link that explains the CCPA or make a quick writeup within the extension (probably the latter) that explains the CCPA and gives more info on it

**Comment by oapostrophe** [comment]
An easy fix could be just linking to the readme on Github, I tried to provide an accessible background discussion there

**Comment by 2br-2b** [comment]
I think that’d be a good idea. The Readme looks fantastic BTW.

Rather than linking to Github, is there a way to pull up the file locally and display that? Doing that might be easier, and since the file is already packaged locally, might as well use it!

**Comment by 2br-2b** [comment]
I ended up linking it towards whatever page is listed in the manifest
