### ISSUE TITLE
Remove CDN

### ISSUE THREAD

**Issue by 2br-2b** [swow2015/Who-sSellingMyInfo-#3]
Can we access the scripts locally from the extension rather than relying on a CDN? It seems redundant to access them via the CDN when we already have them packaged in the script

**Comment by oapostrophe** [comment]
I agree it would be ideal to access from the local directory.  However, I couldn't seem to decipher how to get the right path to the files, hence the workaround with the CDN.  I'll look more into this at a later point unless you are able to figure it out.

**Comment by 2br-2b** [comment]
I got this working in #5 and #6 . You can use `browser.runtime.getURL('./filepath-in-extension-folder')` to get these files.
