### ISSUE TITLE
Add to the Chrome Web Store

### ISSUE THREAD

**Issue by 2br-2b** [swow2015/Who-sSellingMyInfo-#8]

**Comment by 2br-2b** [comment]
If you would like, I could do this build; however, I would like to give the maintainer of the repo the option of doing this himself (and thus controlling its presence there) before I add it.

**Comment by 2br-2b** [comment]
Do you mind if I were to publish this, giving a link to this repo and giving you credit as the author?

**Comment by oapostrophe** [comment]
No, go for it!  Would love to see a link when you put it up

**Comment by 2br-2b** [comment]
I've almost got it ready for review. Is there any chance you can produce a 128x128px version of the icon? That's all that's left to publish it.

**Comment by 2br-2b** [comment]
I needed to make a few small changes (included in #17). For the icon, I just upscaled the extension icon, so feel free to add a better icon if you have one! It's currently pending review in the extension gallery, and I will update this when it is accepted.

**Comment by 2br-2b** [comment]
It's official - https://chrome.google.com/webstore/detail/whos-selling-my-info/fajcnenaofjjodeiglclbihlinbiccek !
