### ISSUE TITLE
Add to Firefox's Add-ons Gallery

### ISSUE THREAD

**Issue by 2br-2b** [swow2015/Who-sSellingMyInfo-#9]
Similar to #8

**Comment by 2br-2b** [comment]
Do you have a domain or a Addon id (per https://extensionworkshop.com/documentation/develop/extensions-and-the-add-on-id/) you would like to use? If so, you could add that to the manifest. If not, Mozilla can generate one automatically.

Also, would you like to do this? If not, I can also manage this.

**Comment by 2br-2b** [comment]
If you want to add this, the process is pretty straightforward. It'll take a bit of time, but it's just filling out forms, submitting screenshots, etc.

**Comment by 2br-2b** [comment]
@swow2015 any update on this? It'd be easier to distribute if the extension is on the AMO, and this way, we can reach more users.

**Comment by oapostrophe** [comment]
Submitted and awaiting review.
